### ISSUE TITLE
Tag the release

### ISSUE THREAD

**Issue by fabaff** [yaleman/aussiebb#10]
Could you please tag the source? This allows distributions to get the complete source from GitHub if they want.

Thanks

**Comment by fabaff** [comment]
Sorry, the source is tagged already.

**Comment by yaleman** [comment]
I've reopened this so I can clean up my workflow and make it work properly - now the package is a dependency in home assistant I should do things right 😂

**Comment by yaleman** [comment]
sorted in d2cab5d
