### ISSUE TITLE
Library doesnt handle VOIP services

### ISSUE THREAD

**Issue by Bre77** [yaleman/aussiebb#12]
https://github.com/home-assistant/core/issues/65625

**Comment by yaleman** [comment]
fixed in https://github.com/yaleman/aussiebb/releases/tag/v0.0.10, #14 adds an additional thing which I'll release as v0.0.11 as soon as you've reviewed it 😄

**Comment by MrEMan** [comment]
Love how quickly these ha things get fixed :)
